SampleWebApp/Controllers/DuplicateSetCookieHeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SampleWebApp.Controllers
{
    /// <summary>
    /// Controller for testing  
    /// </summary>
    public class DuplicateSetCookieHeaderController : Controller
    {
        public ActionResult Index()
        {
            // Abandon the session and clear all cookies to start clean.
            HttpContext.ClearAllCookies();

            return RedirectToAction("Results");
        }

        public async Task<ActionResult> Results()
        {
            var handler = new HttpClientHandler
            {
                AllowAutoRedirect = false
            };
            using(var client = new HttpClient(handler))
            {
                var response = await client.GetAsync("http://localhost:51743/DuplicateSetCookieHeader/SetAuthCookie");

                return View(response.Headers.Single(h => h.Key == "Set-Cookie").Value);
            }
        }
    }
}

SampleWebApp/Controllers/FixedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleWebApp.Controllers
{
    public class FixedController : Controller
    {
        public ActionResult Index()
        {
            // First make sure sessions have been used in the app.
            Session["StartSession"] = "SomeValue";

            return RedirectToAction("ClearCookies");
        }

        public ActionResult ClearCookies()
        {
            // Then abandon the session and clear all cookies to start clean.
            HttpContext.ClearAllCookies();

            return RedirectToAction("SetAuthCookie");
        }

        // Deliberately no SetAuthCookie Action - it is intercepted by middleware.

        public ActionResult Results()
        {
            return View();
        }
    }
}

SampleWebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleWebApp.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

SampleWebApp/Controllers/ReproductionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SampleWebApp.Controllers
{
    public class ReproductionController : Controller
    {
        public ActionResult Index()
        {
            // First make sure sessions have been used in the app.
            Session["StartSession"] = "SomeValue";

            return RedirectToAction("ClearCookies");
        }

        public ActionResult ClearCookies()
        {
            // Then abandon the session and clear all cookies to start clean.
            HttpContext.ClearAllCookies();

            return RedirectToAction("SetAuthCookie");
        }

        // Deliberately no SetAuthCookie Action - it is intercepted by middleware.

        public ActionResult Results()
        {
            return View();
        }
    }
}

SampleWebApp/Views/DuplicateSetCookieHeader/Results.cshtml
@model IEnumerable<string>
@{
    ViewBag.Title = "Set-Cookie Results";
}

<h2>Results for Duplicate Set-Cookie header test</h2>
<p>
    When the Owin cookies are added to the response cookie collection,
    it looks to System.Web that they are new. Because of that, they are
    added once more resulting in duplicate headers...
</p>

<h2>Set-Cookie http headers</h2>
<table>
    <tbody>
        @foreach (var s in Model)
        {
            <tr>
                <td>
                    @s
                    </td>
                </tr>
        }
    </tbody>
</table>

<p>
    @Html.ActionLink("Restart Test", "Index", null, new { @class = "btn btn-default" })
</p>

SampleWebApp/Views/Fixed/Results.cshtml
@{
    ViewBag.Title = "Fixed Results";
}

<h2>Results with Fix</h2>
<p>
    The request cookies typically shows an ASP Session cookie, that has been
    generated by the session system, even though it wasn't present in the
    actual request.
</p>
<p>
    There should also bee an ASP.Net.Cookies auth cookie, both in the cookies
    collection and as a cookie header.
</p>

<h2>Request.Cookies</h2>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Request.Cookies.Count; i++)
        {
            var cookie = Request.Cookies[i];
            <tr>
                <td>@cookie.Name</td>
                <td>@cookie.Value</td>
            </tr>
        }
    </tbody>
</table>

<p>

</p>
<h2>Cookie Header</h2>
@if (Request.Headers["Cookie"] == null)
{
    <em>No Set-Cookie header found in request.</em>
}
else
{
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cookie in Request.Headers["Cookie"].Split(';'))
            {
                var segments = cookie.Split('=');
                <tr>
                    <td>@segments[0]</td>
                    <td>@segments[1]</td>
                </tr>
            }
        </tbody>
    </table>
}

<p>
    @Html.ActionLink("Restart Test", "Index", "Fixed", null, new { @class = "btn btn-default" })
</p>

SampleWebApp/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Owin Cookie Saver</h1>
    <p class="lead">Owin Cookie Saver sample application.</p>
    <p>
        The <a href="https://katanaproject.codeplex.com/workitem/197" target="_blank">Katana bug #197</a> makes
        cookies set through the Owin API sometimes dissappear, especially in applications that use ASP.NET
        Sessions. This is a test application for the Owin Cookie Saver middleware that mitigates the bug
        for cookies set by other owin middleware.
    </p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Bug Reproduction</h2>
        <p>
            Test sequence to prove that cookies set by authentication middleware disappears.
        </p>
        <p>@Html.ActionLink("Start", "Index", "Reproduction", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>Bug Fix</h2>
        <p>
            Test sequence to prove that the cookie survives with the fix middleware activated.
        </p>
        <p>@Html.ActionLink("Start", "Index", "Fixed", null, new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>Duplicate Set-Cookie</h2>
        <p>
            There is an <a href="https://github.com/KentorIT/owin-cookie-saver/issues/1" target="_blank">
            issue</a> in version 1.0.0 of the cookie saver, that sometimes creates
            duplicate Set-Cookie headers. This is a test for that.
        </p>
        <p>@Html.ActionLink("Start", "SetAuthCookie", "DuplicateSetCookieHeader", null, new { @class="btn btn-default" })</p>
    </div>
</div>

SampleWebApp/Views/Reproduction/Results.cshtml
@{
    ViewBag.Title = "Bug Reproduced Results";
}

<h2>Results without Fix</h2>
<p>
    The request cookies typically shows an ASP Session cookie, that has been
    generated by the session system, even though it wasn't present in the
    actual request.
</p>
<p>
    There should also have been an ASP.Net.Cookies auth cookie, but it is
    removed by the bug.
</p>

<h2>Request.Cookies</h2>
<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Request.Cookies.Count; i++)
        {
            var cookie = Request.Cookies[i];
            <tr>
                <td>@cookie.Name</td>
                <td>@cookie.Value</td>
            </tr>
        }
    </tbody>
</table>

<p>

</p>
<h2>Cookie Header</h2>
@if (Request.Headers["Cookie"] == null)
{
    <em>No Set-Cookie header found in request.</em>
}
else
{
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var cookie in Request.Headers["Cookie"].Split(';'))
            {
                var segments = cookie.Split('=');
                <tr>
                    <td>@segments[0]</td>
                    <td>@segments[1]</td>
                </tr>
            }
        </tbody>
    </table>
}

<p>
    @Html.ActionLink("Restart Test", "Index", "Reproduction", null, new { @class = "btn btn-default" })
</p>

SampleWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Owin Cookie Saver</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Owin Cookie Saver", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Kentor</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>